#!/bin/bash

DAEMON="/usr/local/bin/nfq_filter"
OPTS="-c /etc/nfq/nfq_filter.cfg -d"
PIDFILE="/var/run/nfq_filter.pid"
NAME="NFQueue HTTP Filter"

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	
	if [ -f $PIDFILE ]; then
		printf "\n%s\n" "Pid file $PIDFILE already exists, but starting."
		exit
	fi
	
	PID=`$DAEMON $OPTS > /dev/null 2>&1 & echo $!`
	if [ -z $PID ]; then
		printf "%s\n" "Fail"
	else
		printf "%s\n" "Ok"
	fi
;;

stop)
	printf "%-50s" "Stopping $NAME..."
	PID=`cat $PIDFILE`
	if [ -f $PIDFILE ]; then
#		echo $PID
		kill -HUP $PID
		printf "%s\n" "Ok"
		rm -f $PIDFILE
	else
		printf "%s\n" "pidfile not found"
	fi
;;

status)
	printf "%-50s" "Checking $NAME..."
	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
			printf "%s\n" "Process dead but pidfile exists"
		else
			echo "Running"
		fi
	else
		printf "%s\n" "Service not running"
	fi
;;

restart)
	$0 stop
	$0 start
;;

*)
	echo "Usage: $0 {status|start|stop|restart}"
	exit 1

esac
